### INDEX
GET http://localhost:9000/

### ABOUT
GET http://localhost:9000/about

### BLOG
GET http://localhost:9000/blog

### BLOG
POST http://localhost:9000/blog

### BLOG
GET http://localhost:9000/blog?limit=100&published=true